openapi: 3.0.0
info:
  title: Todo API
  version: 1.0.0

paths:
  /todos:
    get:
      summary: Todo 一覧の取得
      responses:
        '200':
          description: 成功
          content:
            application/json:    
              schema:
                $ref: '#/components/schemas/Todos'

    post:
      summary: 新規 Todo の作成
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewTodo'
      responses:
        '201':
          description: 作成成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
    put:
      summary: Todo の更新
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTodo'
      responses:
        '200':
          description: 更新成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
                
    delete:
      summary: Todo の削除
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: 削除成功
          
components:
  schemas:
    Todo:
      type: object
      properties:
        id:
          type: integer
        task:
          type: string
        due_date:
          type: string
          format: date-time
        status:
          type: integer
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
          
    Todos:
      type: array
      items:
        $ref: '#/components/schemas/Todo'
        
    NewTodo:
      type: object
      properties:
        task:
          type: string
        due_date:
          type: string
          format: date-time
          
    UpdateTodo:
      type: object
      properties:
        task:
          type: string
        due_date:
          type: string
          format: date-time
        status:
          type: integer